name: PR Maker
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - master
      - dev
      
permissions:
  contents: write 
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
      - uses: devops-infra/action-pull-request@v0.5.0
        name: PR Maker
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev
          target_branch: master
          title: "Merging ${{ github.ref_name }}"
          body: "**Automated pull request**"
          reviewer: dkoch84
          assignee: dkoch84
          get_diff: true
